Write-Host "========================================="
Write-Host " Network Security Hardening Recommendations"
Write-Host "========================================="
Write-Host ""

Write-Host "[1] Windows Firewall"
Write-Host "Status: GOOD"
Write-Host "Recommendation:"
Write-Host "- Keep all firewall profiles enabled."
Write-Host "- Review inbound rules regularly."
Write-Host "- Remove rules that are no longer needed."
Write-Host ""

Write-Host "[2] Microsoft Defender"
Write-Host "Status: GOOD"
Write-Host "Recommendation:"
Write-Host "- Keep real-time protection enabled."
Write-Host "- Keep security intelligence updated."
Write-Host "- Perform regular scans."
Write-Host ""

Write-Host "[3] Remote Desktop"
Write-Host "Status: GOOD"
Write-Host "Recommendation:"
Write-Host "- Keep RDP disabled if remote access is not required."
Write-Host "- If remote access is needed, use VPN and MFA."
Write-Host ""

Write-Host "[4] SMBv1"
Write-Host "Status: NEEDS VERIFICATION"
Write-Host "Recommendation:"
Write-Host "- Verify SMBv1 with administrative permissions."
Write-Host "- Disable SMBv1 unless a legacy system specifically requires it."
Write-Host "- Use newer SMB versions instead."
Write-Host ""

Write-Host "[5] Listening Ports"
Write-Host "Status: REVIEW"
Write-Host "Detected ports include:"
Write-Host "135, 139, 445 and several dynamic ports."
Write-Host ""
Write-Host "Recommendation:"
Write-Host "- Identify which applications own each listening port."
Write-Host "- Close unnecessary services."
Write-Host "- Do not expose internal Windows services directly to the internet."
Write-Host "- Restrict access with firewall rules."
Write-Host ""

Write-Host "[6] Patch Management"
Write-Host "Status: GOOD"
Write-Host "Recommendation:"
Write-Host "- Continue installing Windows security updates."
Write-Host "- Review updates regularly."
Write-Host "- Include browsers and third-party applications in patching."
Write-Host ""

Write-Host "[7] Network Segmentation"
Write-Host "Status: RECOMMENDED"
Write-Host "Recommendation:"
Write-Host "- Separate employee, guest, server and management devices."
Write-Host "- Use VLANs in a real small business network."
Write-Host "- Block guest devices from reaching internal systems."
Write-Host ""

Write-Host "[8] Account Security"
Write-Host "Status: RECOMMENDED"
Write-Host "Recommendation:"
Write-Host "- Enable MFA for important accounts."
Write-Host "- Use separate administrator accounts."
Write-Host "- Apply least privilege."
Write-Host "- Avoid password reuse."
Write-Host ""

Write-Host "[9] Backups"
Write-Host "Status: RECOMMENDED"
Write-Host "Recommendation:"
Write-Host "- Keep multiple backup copies."
Write-Host "- Store at least one backup offline or off-site."
Write-Host "- Test backup restoration regularly."
Write-Host ""

Write-Host "[10] Logging and Monitoring"
Write-Host "Status: RECOMMENDED"
Write-Host "Recommendation:"
Write-Host "- Monitor firewall and authentication logs."
Write-Host "- Review failed login attempts."
Write-Host "- Keep security logs for incident investigation."
Write-Host ""

Write-Host "========================================="
Write-Host " Hardening Review Completed"
Write-Host "========================================="