Write-Host "========================================="
Write-Host " Basic Security Risk Summary"
Write-Host "========================================="
Write-Host ""

Write-Host "[1] Windows Firewall"
Write-Host "Risk: LOW"
Write-Host "Finding: All firewall profiles are enabled."
Write-Host "My suggestion: Keep the firewall enabled and check the rules sometimes."
Write-Host ""

Write-Host "[2] Microsoft Defender"
Write-Host "Risk: LOW"
Write-Host "Finding: Real-time protection is enabled."
Write-Host "My suggestion: Keep Defender updated and do regular scans."
Write-Host ""

Write-Host "[3] Remote Desktop"
Write-Host "Risk: LOW"
Write-Host "Finding: Remote Desktop is disabled."
Write-Host "My suggestion: Keep it disabled if the company does not need remote access."
Write-Host ""

Write-Host "[4] SMBv1"
Write-Host "Risk: NEEDS REVIEW"
Write-Host "Finding: I could not verify SMBv1 because I did not have admin permission."
Write-Host "My suggestion: Check it with administrator rights and disable SMBv1 if it is not needed."
Write-Host ""

Write-Host "[5] Port 445"
Write-Host "Risk: HIGH ATTENTION"
Write-Host "Finding: Port 445 is listening and it is related with SMB file sharing."
Write-Host "My suggestion: It should not be directly exposed to the internet."
Write-Host ""

Write-Host "[6] Port 139"
Write-Host "Risk: NEEDS REVIEW"
Write-Host "Finding: Port 139 is also related with Windows file sharing."
Write-Host "My suggestion: Only allow it if file sharing is actually needed."
Write-Host ""

Write-Host "[7] Port 135"
Write-Host "Risk: NEEDS REVIEW"
Write-Host "Finding: Port 135 is used by Windows RPC services."
Write-Host "My suggestion: External access should be restricted by the firewall."
Write-Host ""

Write-Host "[8] Print Spooler"
Write-Host "Risk: NEEDS REVIEW"
Write-Host "Finding: The spoolsv process is running and listening."
Write-Host "My suggestion: If the computer does not use a printer, this service can be reviewed."
Write-Host ""

Write-Host "[9] Extra Applications"
Write-Host "Risk: NEEDS REVIEW"
Write-Host "Finding: Applications like Spotify were listening on network ports."
Write-Host "My suggestion: Business computers should not have unnecessary applications."
Write-Host ""

Write-Host "[10] Windows Updates"
Write-Host "Risk: LOW"
Write-Host "Finding: Recent Windows updates were found."
Write-Host "My suggestion: Continue installing security updates regularly."
Write-Host ""

Write-Host "========================================="
Write-Host " Risk Summary Finished"
Write-Host "========================================="